#!/bin/sh

if [ ! -e /home/ami-setup/.git ]; then
echo "Must clone ami-setup to /home/ami-setup"
exit 1
fi


yum -y --skip-broken shell <<EOF
install patch
install ed
install git
install gcc
install make
install perl
install ntp
install ltrace
install nc
install nmap
install wireshark
install rsync
install perl-JSON
install vim-enhanced
install perl-Digest-SHA
install perl-Digest-SHA1 
install perl-Digest-MD5
install perl-Cache-Memcached
install perl-Net-DNS
install perl-MIME-Lite 
install readline-devel
install memcached
install httpd24
install httpd24-devel 
install mod24_ssl 
install msmtp
install perl-Net-Amazon-S3
install perl-Net-Amazon-EC2
install iotop
install xauth
install glibc-static
install zlib-static
install libcurl-devel
install tidy
install perltidy
install perl-LWP-Protocol-https
install perl-MongoDB
install make
install lsof
install psmisc
install sysstat
install dstat 
install lvm2
install bind-utils
install traceroute
install mtr
install zip
install unzip
install bzip2
install lzma
install tree
install time
install sqlite
install rpm-build
install perl-Term-ReadLine-Gnu
install perl-Term-ReadLine-Perl
install mailx
install iperf
install fping
install ethtool
install dos2unix
install dnsmasq
install sendmail
install sendmail-cf
install telnet
install strace
install ltrace
install perl-Sys-Syslog
install glibc-devel
install gcc-c++
install pcre-devel
install sqlite-devel
install openssl-devel
install tidy-devel
install perl-CGI
install mysql
install yum-utils
install python-pip
install perl-CPAN
upgrade
run
EOF

pip install --upgrade s3cmd

#yum -y --skip-broken --enablerepo=epel shell <<EOF
#install msmtp
#upgrade
#run
#EOF

rm -rf /root/.cpan/build
echo "" | perl -MCPAN -e shell

perl -MCPAN -e shell <<EOF
notest install Term::ReadLine::Perl
notest install Term::ReadLine::Gnu
notest install Config::AutoConf
notest install Path::Tiny
notest install MongoDB
EOF

rm -rf /root/.cpan/build
rm -rf /root/perl5
