#!/bin/sh

if [ ! -e /home/ami-setup/.git ]; then
echo "Must clone ami-setup to /home/ami-setup"
exit 1
fi

yum -y upgrade

chown -R root:root /home/ami-setup/overlay
cd /home/ami-setup/overlay || exit 1
find . -print | cpio -pdmuv /

ed /root/.bashrc <<EOF
g/alias/d
.
w
q
EOF

ed /root/.cshrc <<EOF
g/alias/d
.
w
q
EOF

# Set up ssh access
ed /etc/ssh/sshd_config <<EOF
g/PasswordAuthentication/d
g/PermitRootLogin/d
g/MaxAuthTries/d
a
PermitRootLogin yes
PasswordAuthentication yes
# Allow more key attempts
MaxAuthTries 20
.
w
q
EOF

# Create dir for rsyslog
mkdir -p /home/local

# Install Nathan's rclocal scripts
yum -y localinstall /home/ami-setup/rpms/*.rpm

# Clean up any cloud-init stuff
rm -rf /var/lib/cloud/data
rm -rf /var/lib/cloud/instance
rm -rf /var/lib/cloud/instances/*

# 
rm -f /etc/update-motd.d/*

# Remove 'fedora' userid if it was set up

userdel -f fedora
rm -rf /home/fedora

userdel -f ec2-user
rm -rf /home/ec2-user

# enable ntp
chkconfig ntpdate on
chkconfig ntpd on

cat >/etc/ntp/step-tickers <<EOF
0.amazon.pool.ntp.org
1.amazon.pool.ntp.org
2.amazon.pool.ntp.org
3.amazon.pool.ntp.org
EOF

rm -f /etc/sudoers.d/cloud-init

cat /dev/null > /etc/motd

git config --global push.default simple

echo "######################"
echo "Manual Action Required"
echo "######################"
echo "Populate ~root/.awssecret and ~root/.s3cfg with AWS deployment keys mode 0600."
echo ""
